export const allRoutes = {
  home: '/home',
  login: '/login',
  register: '/register',
  messages: '/messages',
  socialLogin: '/social-login',
  notifications: '/notifications',
  inbox: '/inbox',
  termsAndConditions: '/termsOfService',
  privacyPolicy: '/privacyPolicy',
  cookiesPolicy: '/cookiePolicy',
  settings: {
    index: '/settings',
    account: '/settings/account',
    changePassword: '/settings/change-password',
    blockUser: '/settings/blocked-user',
    deleteAccount: '/settings/delete-account',
    help: '/settings/help',
  },
  post: '/post',
  profile: '/profile',
  recoveryCodes: '/recovery-codes',
};
